language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.2.3
- 2.1.8
- 2.1.2
script:
  - bundle exec rake all
  - bundle exec rake yard
addons:
    code_climate:
        repo_token: ddaffc1830a7f175bcca559e29619daee62aa145360e2dfbc9dd8e9ac5ce14fb
